/* eslint-disable */
// prettier-ignore
// This file is automatically generated by typings-for-css-modules.
// Don't change it directly!

declare namespace StylesModuleSassNamespace {
  export interface IStylesModuleSass {
    'root': string;
  }
}

declare const StylesModuleSassModule: StylesModuleSassNamespace.IStylesModuleSass & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StylesModuleSassNamespace.IStylesModuleSass
}

export = StylesModuleSassModule
